### ISSUE TITLE
Serialize empty ADT constructor as Array[code] instead of code alone

### ISSUE THREAD

**Issue by SX91** [TokTok/hs-msgpack-types#2]
Now multiple constuctor ADT is serialized as:

- code
- [code, value]
- [code, [value, ...]]

I think `code` alone is ambiguous. It is deserialized as `integer` and `integer` can be deserialized to `Int`, `Float` or `Double`. So if you have `Maybe a`, `Nothing` is `0` while `Just a` is `[1, Object]`.

So I propose empty constructor serialization as `[code]`.

**Comment by iphydf** [comment]
I'm ok with changing this, but why? What does the ambiguity break?

**Comment by SX91** [comment]
Because it's easier to decode it in other languages (ex. Rust, Python etc.).

**Comment by iphydf** [comment]
Merged.
