### ISSUE TITLE
a new version for GHC 8.8

### ISSUE THREAD

**Issue by kazu-yamamoto** [TokTok/hs-msgpack-types#20]
`master` is ready for GHC 8.8.
Would you release a new version to rescue GHC 8.8 users?

**Comment by maksbotan** [comment]
I also would like to see this. Once you make a release, `data-msgpack-types` and `data-msgpack` will get included into stackage nightly and then into LTS-15 once it's out (which probably is gonna happen rather soon).

**Comment by maksbotan** [comment]
@iphydf hey!
It's now official, LTS-15 with GHC-8.8 will be out in a week: https://www.stackage.org/blog/2020/02/upcoming-lts-15-ghc-8-8-2

You still have time to get your packages into it. Can you please make a new Hackage release?

**Comment by iphydf** [comment]
0.0.3 is now on hackage.
